### PR TITLE
Update as per icp4d 2.5

### PR DESCRIPTION
**Pull request by sandhya-nayak**
Update as per ICP4D 2.5 and workshop.
Also add fix for #16.

### CODE REVIEW

**Comment by scottdangelo** [comment]
Are you trying to sync downstream with upstream here @sandhya-nayak ? I'd like to do that in a more coordinated way, with mostly one person managing that process.

**Review by scottdangelo — CHANGES_REQUESTED** [review]
I'm not sure why you are working on this downstream repository.

**Comment by sandhya-nayak** [comment]
> Are you trying to sync downstream with upstream here @sandhya-nayak ? I'd like to do that in a more coordinated way, with mostly one person managing that process.

@scottdangelo Yes - I was trying to sync downstream with upstream.

**Comment by scottdangelo** [comment]
OK, sorry. I was thinking of an entirely different repository! Too many different things to sync up....I'll have a look at this on Thursday.

**Review by scottdangelo — APPROVED** [review]

**Pull request merged**
